In [30]:
'''Importing modules'''
import numpy as np
import scipy.linalg as sc
import collections

In [31]:
'''Taking number of web pages as input'''
n = int(input("Enter the number of web pages: - "))

Enter the number of web pages: - 4


In [32]:
graph = np.zeros([n, n], dtype = float)

In [33]:
'''Taking number of edges as input'''
edge = int(input("Enter the number of edges: -"))

Enter the number of edges: -3


In [34]:
'''Taking input of edges'''
for i in range(edge):
    x,y = [int(x) for x in input().split()]
    graph[x-1][y-1] = 1

1 2
2 3
3 4


In [35]:
'''Setting value of alpha'''
alpha = 0.1

In [36]:
'''Calculating the graph matrix'''

for i in range(n):
    sum = 0
    for j in range(n):
        sum = sum+graph[i][j]
    for j in range(n):
        if sum!=0:
            graph[i][j] = graph[i][j]/sum
            graph[i][j] = graph[i][j]*(1-alpha)
            graph[i][j] = graph[i][j]+(alpha/n)

In [37]:
graph

array([[0.025, 0.925, 0.025, 0.025],
       [0.025, 0.025, 0.925, 0.025],
       [0.025, 0.025, 0.025, 0.925],
       [0.   , 0.   , 0.   , 0.   ]])

In [38]:
#Using linear algebra packages, with teleportations

In [39]:
v, V = np.linalg.eig(graph.T)
left_principal_eigen = V[:, 0].T

In [40]:
'''Linear algebra left eigenvector calculations'''
w,vl, vr = sc.eig(graph, left=True)
eVals = w
eVecs = vl
order = np.absolute(eVals).argsort()[::-1]

eVals = eVals[order]
eVecs = eVecs[:, order]
r = eVecs[:, 0]
res = np.real(r/np.sum(r))


In [41]:
res

array([0.025     , 0.08779424, 0.24551889, 0.64168687])

In [42]:
dic = {};
for i in range(len(res)):
    dic[i] = res[i]
odic = {k+1: v for k, v in sorted(dic.items(), key=lambda item: item[1])}

In [43]:
ranks = list(odic.keys())
ranks.reverse()
ranks

[4, 3, 2, 1]

In [44]:
#Using Power Iteration method, with teleportations

In [45]:
mgraph = np.asmatrix(graph)
prev = np.zeros(n)
prev[0] = 1
prev = np.asmatrix(prev)

In [46]:
for i in range(1000):
    prev = prev@graph
    
res = np.asarray(np.asarray(prev))
res = np.asarray(res[0])

In [47]:
dic = {};
for i in range(len(res)):
    dic[i] = res[i]
odic = {k+1: v for k, v in sorted(dic.items(), key=lambda item: item[1])}

odic

ranks = list(odic.keys())
ranks.reverse()
ranks

[4, 3, 2, 1]

In [20]:
#Without teleportations
n = int(input("Enter the number of web pages: - "))

Enter the number of web pages: - 4


In [21]:
graph = np.zeros([n, n], dtype = float)

In [22]:
edge = int(input("Enter the number of edges: -"))

Enter the number of edges: -5


In [23]:
for i in range(edge):
    x,y = [int(x) for x in input().split()]
    graph[x-1][y-1] = 1

1 2
3 4
3 2
4 3
4 2


In [24]:
for i in range(n):
    sum = 0
    for j in range(n):
        sum = sum+graph[i][j]
    for j in range(n):
        if sum!=0:
            graph[i][j] = graph[i][j]/sum
            graph[i][j] = graph[i][j]

In [25]:
graph

array([[0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5],
       [0. , 0.5, 0.5, 0. ]])

In [26]:
v, V = np.linalg.eig(graph.T)
left_principal_eigen = V[:, 0].T

In [27]:
w,vl, vr = sc.eig(graph, left=True)
eVals = w
eVecs = vl
order = np.absolute(eVals).argsort()[::-1]

eVals = eVals[order]
eVecs = eVecs[:, order]
r = eVecs[:, 0]
res = np.real(r/np.sum(r))

In [28]:
dic = {};
for i in range(len(res)):
    dic[i] = res[i]
odic = {k+1: v for k, v in sorted(dic.items(), key=lambda item: item[1])}

ranks = list(odic.keys())
ranks.reverse()
ranks

[2, 3, 4, 1]

In [29]:
#Power Iteration, without teleportations
mgraph = np.asmatrix(graph)
prev = np.zeros(n)
prev[0] = 1
prev = np.asmatrix(prev)

for i in range(1000):
    prev = prev@graph
    
res = np.asarray(np.asarray(prev))
res = np.asarray(res[0])

dic = {};
for i in range(len(res)):
    dic[i] = res[i]
odic = {k+1: v for k, v in sorted(dic.items(), key=lambda item: item[1])}

odic

ranks = list(odic.keys())
ranks.reverse()
ranks

[4, 3, 2, 1]